# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
# https://circleci.com/docs/2.0/configuration-reference
version: 2
jobs:
  run_test:
    docker:
      - image: circleci/ruby:2.6.2-node
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test
workflows:
  version: 2
  build:
    jobs:
      - run_test
